services:
    bacnet_tests:
        entrypoint: sh /home/tests.sh
        environment:
            - EXPECTED=/home/expected
            - PROPERTY_MAPPING_FILE=/home/property_mapping.txt
            - SKIP_READ=$SKIP_READ
        image: mfrancis95/bacnet-stack
        network_mode: host
        volumes:
            - .:/home
            - $EXPECTED:/home/expected
version: '3'
